# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Augur < Formula
  desc "git blame for AI — traces code back to the Claude session that wrote it"
  homepage "https://github.com/zpenka/augur"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zpenka/augur/releases/download/v0.1.0/augur_darwin_x86_64.tar.gz"
      sha256 "28b012cf957d5c9c5a310c81b879d3d44562250e1eb77949c74f50ed81bb3de2"

      define_method(:install) do
        bin.install "augur"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zpenka/augur/releases/download/v0.1.0/augur_darwin_arm64.tar.gz"
      sha256 "8ec0cfca387b60adb8533bd909b3ca073a7c32e7ad290440f383d6586f741da6"

      define_method(:install) do
        bin.install "augur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zpenka/augur/releases/download/v0.1.0/augur_linux_x86_64.tar.gz"
      sha256 "09ccb63aa47887c770d8c20b66291add7337976fb651bf8866c65ddfc16654b9"
      define_method(:install) do
        bin.install "augur"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zpenka/augur/releases/download/v0.1.0/augur_linux_arm64.tar.gz"
      sha256 "fe617c431c371538236a70f23a186c513bef9e66e80149d0837bad0dfa874c05"
      define_method(:install) do
        bin.install "augur"
      end
    end
  end

  test do
    system "#{bin}/augur", "--version"
  end
end
