# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "Keyboard-driven TUI for browsing Claude Code session history"
  homepage "https://github.com/zpenka/lore"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zpenka/lore/releases/download/v0.7.1/lore_darwin_x86_64.tar.gz"
      sha256 "a180b8c83371eaa1d332407c0557b0a150c66cf13cad0f5f00accc95f27fbc27"

      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zpenka/lore/releases/download/v0.7.1/lore_darwin_arm64.tar.gz"
      sha256 "c920c4007d598bf98146b19a7c553dee0b8ff0933e1e058b5481c430866a26e3"

      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zpenka/lore/releases/download/v0.7.1/lore_linux_x86_64.tar.gz"
      sha256 "55ebc1b377a800073f2868d06fea85ffb90e3a4549e0c2829e19c66c749b9d55"
      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zpenka/lore/releases/download/v0.7.1/lore_linux_arm64.tar.gz"
      sha256 "662775d8212695372204316a8457cc3e968ad51adc940f0b55b80dcfabba2453"
      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  test do
    system "#{bin}/lore", "--version"
  end
end
